### ISSUE TITLE
一个框架使用的问题

### ISSUE THREAD

**Issue by xia0lei** [Manistein/SparkServer#20]
我正在寻找一个c#的actor轻量服务器框架，也是因为战斗主要是用c#写的，您写的这个很适合我的需求，我在研读的过程中有一个关于项目实用的问题，您的gateclientcase里面我看到发送数据包是使用了框架里面的TcpClient类，那这个类中包含了Session, InBoundManager和OutBoundManager相关的类，我想请问下，就是使用发送数据包时，也是让Unity客户端的同学去使用TCPClient相关的类的吗？

**Comment by Manistein** [comment]
可以参考这个类，根据项目需求去修改。因为TCPClient是SparkServer的集群机制的一个部分。它有针对内部节点，进行一些特殊的处理，比如大包拆分等，有特定的编码方式，不一定适合你们c2s的应用场景。

**Comment by xia0lei** [comment]
我看你做这个项目的初衷也是为了复用c#的战斗代码，那你这边有一个GateWay, 客户端和SparkServer交互时，想必也是和这个GateWay做通讯，是怎样的流程呢？

**Comment by Manistein** [comment]
我刚才重新过了一下TCPClient的代码，它并没有针对集群数据包进行编码解码，而是负责数据包的收发。你们可以尝试直接使用TCPClient来作为客户端的网络库使用，不过可能需要做一些修改。我们之前的项目，unity客户端是不能直连战斗服的，因此是本质也是服务器内部的socket通信。gateway组件，确实是用来处理客户端socket通信的。

**Comment by Manistein** [comment]
http://manistein.club/post/server/csharp/csharp%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%A1%86%E6%9E%B6%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0/
网络库的详细设计，可以参考这篇

**Comment by xia0lei** [comment]
和我想的也大致一样，主要是我们这边的项目是一个射击类的游戏，准备用帧同步，我们现在的结构是有一个skynet节点作为用户数据逻辑的处理 ，SparkServer这里作为战斗服，但我的想法是战斗时，让客户端直连战斗服，不然的话我可能要通过skynet转发，担心有较大的延迟，所以才有了以上的疑问，那我再想想解决方案。

**Comment by Manistein** [comment]
SparkServer可以客户端直连的

**Comment by xia0lei** [comment]
那你直连也是需要通过TCPClient作为网路库的不是吗？

**Comment by Manistein** [comment]
可以用

**Comment by Manistein** [comment]
但是，不太了解你们具体的需求，所以你们有可能需要做一些适配自己项目的修改。

**Comment by xia0lei** [comment]
嗯 ，这个我明白，我已经把框架中的sproto换成了protobuf 几个测试案例也已经修改跑了下， 其他的需求我再想想方案 ， 我们客户端这边已经有自己的网络库，所以要综合性的考量一下。
